# Generated by Django 5.2.17 on 2026-10-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_pendinginvitation_and_more"),
        ("tasks", "0002_task_overdue_notified_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("comment_added", "Comment Added"),
                            ("status_changed", "Status Changed"),
                            ("task_overdue", "Task Overdue"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notif_recipient_recent_idx",
                    ),
                    models.Index(
                        condition=models.Q(("read_at__isnull", True)),
                        fields=["recipient"],
                        name="notif_unread_recipient_idx",
                    ),
                ],
            },
        ),
    ]
